#! /bin/bash -e
#

cd $(dirname $0)/..

trap "docker-compose down --volumes" 0
docker volume create --name ruby2.4-bundle-cache > /dev/null

docker-compose run --rm dev sh -c 'bundle check > /dev/null || bundle install'
docker-compose run --rm dev bundle exec "${@-bash}"
